import type { Effect, EffectInput } from "@/types";

export const OPTIONS_WIDTH = 400;

export const EFFECT_NAMES: Record<Effect, string> = {
  none: "Ninguno",
  tint: "Tint",
  warp: "Warp",
  "simple-crt-vhs": "Simple CRT VHS",
  "crt-vhs": "CRT VHS",
  crt: "CRT",
  "film-grain": "Film Grain",
  "lens-array": "Lens Array",
  "metal-core": "Metal Core",
  posterize: "Posterize",
  sepia: "Sepia",
  ps1: "PS1 ",
  "dithering-plus-color-palettes": "Dithering + Color Palettes",
  "analog-monochrome-monitor": "Analog Monochrome Monitor",
  bloom: "Bloom",
};

export const EFFECT_DEFAULTS: Record<Exclude<Effect, "none">, Record<string, EffectInput>> = {
  tint: {
    color: {
      key: "color",
      label: "Color",
      type: "color",
      value: "#ff0055",
    },
    opacity: {
      key: "opacity",
      label: "Opacity",
      type: "number",
      value: 0.8,
      min: 0,
      max: 1,
    },
  },
  warp: {
    intensity: {
      key: "intensity",
      label: "Intensity",
      type: "number",
      value: 0.05,
      min: 0,
      max: 1,
    },
  },
  "simple-crt-vhs": {
    scanlines1: {
      key: "scanlines1",
      label: "Scanlines 1",
      type: "number",
      value: 500.0,
      min: 0.0,
      max: 2000.0,
      step: 1.0,
    },
    scanlines2: {
      key: "scanlines2",
      label: "Scanlines 2",
      type: "number",
      value: 25.0,
      min: 0.0,
      max: 200.0,
      step: 1.0,
    },
    scanReduction: {
      key: "scanReduction",
      label: "Scan Reduction",
      type: "number",
      value: 0.1,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    vinnetteAlpla: {
      key: "vinnetteAlpla",
      label: "Vinnette Alpha",
      type: "number",
      value: 1.0,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    vinnetteInnerRadius: {
      key: "vinnetteInnerRadius",
      label: "Vinnette Inner Radius",
      type: "number",
      value: 0.0,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    vinnetteOuterRadius: {
      key: "vinnetteOuterRadius",
      label: "Vinnette Outer Radius",
      type: "number",
      value: 1.0,
      min: 0.0,
      max: 2.0,
      step: 0.01,
    },
  },
  "crt-vhs": {
    scanlinesOpacity: {
      key: "scanlinesOpacity",
      label: "Scanlines_Opacity",
      type: "number",
      value: 0.4,
      min: 0,
      max: 1,
    },
    scanlinesWidth: {
      key: "scanlinesWidth",
      label: "Scanlines_Width",
      type: "number",
      value: 0.25,
      min: 0,
      max: 1,
    },
    grilleOpacity: {
      key: "grilleOpacity",
      label: "Grille_Opacity",
      type: "number",
      value: 0.3,
      min: 0,
      max: 1,
    },
    pixelate: {
      key: "pixelate",
      label: "Pixelate",
      type: "boolean",
      value: true,
    },
    roll: {
      key: "roll",
      label: "Roll",
      type: "boolean",
      value: true,
    },
    rollSpeed: {
      key: "rollSpeed",
      label: "Roll_Speed",
      type: "number",
      value: 8.0,
      min: 0,
      max: 32,
    },
    rollSize: {
      key: "rollSize",
      label: "Roll_Size",
      type: "number",
      value: 15.0,
      min: 0,
      max: 100,
      step: 1,
    },
    rollVariation: {
      key: "rollVariation",
      label: "Roll_Variation",
      type: "number",
      value: 1.8,
      min: 0,
      max: 10,
    },
    distortIntensity: {
      key: "distortIntensity",
      label: "Distort_Intensity",
      type: "number",
      value: 0.05,
      min: 0,
      max: 1,
    },
    noiseOpacity: {
      key: "noiseOpacity",
      label: "Noise_Opacity",
      type: "number",
      value: 0.4,
      min: 0,
      max: 1,
    },
    noiseSpeed: {
      key: "noiseSpeed",
      label: "Noise_Speed",
      type: "number",
      value: 5.0,
      min: 0,
      max: 50,
    },
    staticNoiseIntensity: {
      key: "staticNoiseIntensity",
      label: "Static_Noise_Intensity",
      type: "number",
      value: 0.06,
      min: 0,
      max: 1,
    },
    aberration: {
      key: "aberration",
      label: "Aberration",
      type: "number",
      value: 0.03,
      min: 0,
      max: 1,
    },
    brightness: {
      key: "brightness",
      label: "Brightness",
      type: "number",
      value: 1.4,
      min: 0,
      max: 10,
    },
    discolor: {
      key: "discolor",
      label: "Discolor",
      type: "boolean",
      value: true,
    },
    warpAmount: {
      key: "warpAmount",
      label: "Warp_Amount",
      type: "number",
      value: 1.0,
      min: 0,
      max: 10,
      step: 1,
    },
    clipWarp: {
      key: "clipWarp",
      label: "Clip_Warp",
      type: "boolean",
      value: false,
    },
    vignetteIntensity: {
      key: "vignetteIntensity",
      label: "Vignette_Intensity",
      type: "number",
      value: 0.4,
      min: 0,
      max: 1,
    },
    vignetteOpacity: {
      key: "vignetteOpacity",
      label: "Vignette_Opacity",
      type: "number",
      value: 0.5,
      min: 0,
      max: 1,
    },
  },
  crt: {
    pixelSize: {
      key: "pixelSize",
      label: "Pixel_Size",
      type: "number",
      value: 8.0,
      min: 1,
      max: 50,
      step: 1,
    },
  },
  "film-grain": {
    amount: {
      key: "amount",
      label: "Amount",
      type: "number",
      value: 1.25,
      min: 0.0,
      max: 100.0,
      step: 0.01,
    },
    speed: {
      key: "speed",
      label: "Speed",
      type: "number",
      value: 1.0,
      min: 0.1,
      max: 5.0,
      step: 0.1,
    },
  },
  "lens-array": {
    gridSize: {
      key: "gridSize",
      label: "Grid_Size",
      type: "number",
      value: 50.0,
      min: 1,
      max: 100,
      step: 1,
    },
    curvature: {
      key: "curvature",
      label: "Curvature",
      type: "number",
      value: 0.25,
      min: 0,
      max: 1,
    },
    gridAngle: {
      key: "gridAngle",
      label: "Grid_Angle",
      type: "number",
      value: 0.0,
      min: 0,
      max: 1,
    },
    shape: {
      key: "shape",
      label: "Shape",
      type: "select",
      value: "circle",
      options: {
        circle: {
          key: "circle",
          label: "Circle",
          value: 0,
        },
        diamong: {
          key: "diamong",
          label: "Diamong",
          value: 1,
        },
        square: {
          key: "square",
          label: "Square",
          value: 2,
        },
      },
    },
    scale: {
      key: "scale",
      label: "Scale",
      type: "array-2",
      value: [1, 1],
      min: 0,
      max: 100,
      step: 1,
    },
    stagger: {
      key: "stagger",
      label: "Stagger",
      type: "boolean",
      value: true,
    },
  },
  "metal-core": {
    exposure: {
      key: "exposure",
      label: "Exposure",
      type: "number",
      value: 1.0,
      min: 0,
      max: 2,
    },
    contrast: {
      key: "contrast",
      label: "Contrast",
      type: "number",
      value: 1.05,
      min: 0,
      max: 2,
    },
    saturation: {
      key: "saturation",
      label: "Saturation",
      type: "number",
      value: 0.9,
      min: 0,
      max: 2,
    },
    enablePixelate: {
      key: "enablePixelate",
      label: "Enable_Pixelate",
      type: "boolean",
      value: true,
    },
    pixelFactor: {
      key: "pixelFactor",
      label: "Pixel_Factor",
      type: "number",
      value: 2.0,
      min: 1,
      max: 100,
    },
    enablePosterize: {
      key: "enablePosterize",
      label: "Enable_Posterize",
      type: "boolean",
      value: true,
    },
    colorLevels: {
      key: "colorLevels",
      label: "Color_Levels",
      type: "number",
      value: 8.0,
      min: 1,
      max: 64,
      step: 1,
    },
    ditherStrength: {
      key: "ditherStrength",
      label: "Dither_Strength",
      type: "number",
      value: 0.35,
      min: 0,
      max: 1,
    },
    chromAberration: {
      key: "chromAberration",
      label: "Chrom_Aberration",
      type: "number",
      value: 0.35,
      min: 0,
      max: 1,
    },
    vignetteStrength: {
      key: "vignetteStrength",
      label: "Vignette_Strength",
      type: "number",
      value: 1.0,
      min: 0,
      max: 10,
    },
    grainStrength: {
      key: "grainStrength",
      label: "Grain_Strength",
      type: "number",
      value: 0.2,
      min: 0,
      max: 10,
    },
    tintColor: {
      key: "tintColor",
      label: "Tint_Color",
      type: "color",
      value: "#f2ffe6",
    },
    tintStrength: {
      key: "tintStrength",
      label: "Tint_Strength",
      type: "number",
      value: 0.15,
      min: 0,
      max: 1,
    },
  },
  posterize: {
    noiseScale: {
      key: "noiseScale",
      label: "Noise_Scale",
      type: "number",
      value: 1.0,
      min: 1,
      max: 100,
      step: 1,
    },
    colorLevels: {
      key: "colorLevels",
      label: "Color_Levels",
      type: "number",
      value: 4,
      min: 0,
      max: 64,
      step: 1,
    },
    ditherStrength: {
      key: "ditherStrength",
      label: "Dither_Strength",
      type: "number",
      value: 0.5,
      min: 0,
      max: 1,
    },
  },
  sepia: {
    noiseScale: {
      key: "noiseScale",
      label: "Noise Scale",
      type: "number",
      value: 4.0,
      min: 1.0,
      max: 10.0,
      step: 0.1,
    },
    vignetteStrength: {
      key: "vignetteStrength",
      label: "Vignette Strength",
      type: "number",
      value: 0.7,
      min: 0.1,
      max: 2.0,
      step: 0.05,
    },
    sepiaStrength: {
      key: "sepiaStrength",
      label: "Sepia Strength",
      type: "number",
      value: 0.85,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    contrast: {
      key: "contrast",
      label: "Contrast",
      type: "number",
      value: 1.2,
      min: 0.5,
      max: 2.0,
      step: 0.05,
    },
    glowRange: {
      key: "glowRange",
      label: "Glow Range",
      type: "number",
      value: 12.0,
      min: 1.0,
      max: 30.0,
      step: 0.5,
    },
    glowStrength: {
      key: "glowStrength",
      label: "Glow Strength",
      type: "number",
      value: 0.75,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    glowFalloff: {
      key: "glowFalloff",
      label: "Glow Falloff",
      type: "number",
      value: 2.0,
      min: 0.5,
      max: 4.0,
      step: 0.1,
    },
    dirtStrength: {
      key: "dirtStrength",
      label: "Dirt Strength",
      type: "number",
      value: 0.4,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    dirtScale: {
      key: "dirtScale",
      label: "Dirt Scale",
      type: "number",
      value: 8.0,
      min: 1.0,
      max: 100.0,
      step: 1.0,
    },
  },
  ps1: {
    resolutionX: {
      key: "resolutionX",
      label: "Resolution X",
      type: "number",
      value: 320,
      min: 64,
      max: 1920,
      step: 1,
    },
    resolutionY: {
      key: "resolutionY",
      label: "Resolution Y",
      type: "number",
      value: 240,
      min: 64,
      max: 1080,
      step: 1,
    },
    colorBitDepth: {
      key: "colorBitDepth",
      label: "Color Bit Depth",
      type: "number",
      value: 4,
      min: 1,
      max: 8,
      step: 1,
    },
    ditherStrength: {
      key: "ditherStrength",
      label: "Dither Strength",
      type: "number",
      value: 0.03,
      min: 0.0,
      max: 0.2,
      step: 0.001,
    },
    jitterAmount: {
      key: "jitterAmount",
      label: "Jitter Amount",
      type: "number",
      value: 0.008,
      min: 0.0,
      max: 0.05,
      step: 0.001,
    },
    jitterSpeed: {
      key: "jitterSpeed",
      label: "Jitter Speed",
      type: "number",
      value: 1.2,
      min: 0.0,
      max: 10.0,
      step: 0.1,
    },
    jitterFrequency: {
      key: "jitterFrequency",
      label: "Jitter Frequency",
      type: "number",
      value: 180.0,
      min: 1.0,
      max: 500.0,
      step: 1.0,
    },
    chromaticAberrationStrength: {
      key: "chromaticAberrationStrength",
      label: "Chromatic Aberration Strength",
      type: "number",
      value: 0.015,
      min: 0.0,
      max: 0.1,
      step: 0.001,
    },
    vignetteStrength: {
      key: "vignetteStrength",
      label: "Vignette Strength",
      type: "number",
      value: 0.8,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    vignetteRadius: {
      key: "vignetteRadius",
      label: "Vignette Radius",
      type: "number",
      value: 0.9,
      min: 0.0,
      max: 2.0,
      step: 0.05,
    },
  },
  "dithering-plus-color-palettes": {
    rows: {
      key: "rows",
      label: "rows",
      type: "number",
      value: 4.0,
      min: 1.0,
      max: 32.0,
      step: 1.0,
    },
    cols: {
      key: "cols",
      label: "cols",
      type: "number",
      value: 4.0,
      min: 1.0,
      max: 32.0,
      step: 1.0,
    },
    ditherSize: {
      key: "ditherSize",
      label: "ditherSize",
      type: "number",
      value: 1.0,
      min: 1.0,
      max: 16.0,
      step: 1.0,
    },
    ditherAmount: {
      key: "ditherAmount",
      label: "ditherAmount",
      type: "number",
      value: 0.5,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    pal: {
      key: "pal",
      label: "Palette",
      type: "select",
      value: "game_boy",
      options: {
        game_boy: {
          key: "game_boy",
          label: "GameBoy",
          value: ["#0f380f", "#306230", "#8bac0f", "#9bbc0f"],
        },
        game_boy_pocket: {
          key: "game_boy_pocket",
          label: "GameBoy Pocket",
          value: ["#1a1a1a", "#3d3448", "#7a6878", "#a89aa8", "#ccc4cc", "#e8e4e8"],
        },
        amber: {
          key: "amber",
          label: "Amber",
          value: ["#0a0400", "#3d1a00", "#b34400", "#ffaa00"],
        },
        thermal: {
          key: "thermal",
          label: "Thermal",
          value: ["#000000", "#1a0030", "#4b0082", "#8b0000", "#cc2200", "#ff6600", "#ffcc00", "#ffffff"],
        },
        vaporwave: {
          key: "vaporwave",
          label: "Vaporwave",
          value: ["#0d0221", "#190935", "#2e1760", "#7b2d8b", "#c264ce", "#ff6ad2", "#c774e8", "#f8a8ff"],
        },
        nuclear: {
          key: "nuclear",
          label: "Nuclear",
          value: ["#0a1a00", "#1a3300", "#2d5500", "#4d8000", "#7abf00", "#b3e600", "#e6ff4d", "#ffffcc"],
        },
        blood_moon: {
          key: "blood_moon",
          label: "Blood Moon",
          value: ["#0a0000", "#1a0000", "#330000", "#660000", "#990000", "#cc3300", "#ff6600", "#ffaa66"],
        },
        arctic: {
          key: "arctic",
          label: "Arctic",
          value: ["#000a1a", "#001433", "#002266", "#003399", "#0055cc", "#4488ee", "#88bbff", "#cce5ff"],
        },
        noir: {
          key: "noir",
          label: "Noir",
          value: ["#000000", "#111111", "#222222", "#444444", "#777777", "#aaaaaa", "#cccccc", "#ffffff"],
        },
        sunset: {
          key: "sunset",
          label: "Sunset",
          value: ["#0a0000", "#3d0a0a", "#7a1a1a", "#c43d3d", "#e87a3d", "#f5b86e", "#ffe4a0", "#fff5e8"],
        },
        liminal: {
          key: "liminal",
          label: "Liminal",
          value: ["#050508", "#0e1021", "#1a1d3d", "#2a3060", "#4060a0", "#7090c8", "#a8c0e0", "#e8f0ff"],
        },
        ultraviolet: {
          key: "ultraviolet",
          label: "Ultraviolet",
          value: ["#0d0510", "#1a0a22", "#2d0d3d", "#44156b", "#6b1d9e", "#9b3dd4", "#c97af5", "#eddaff"],
        },
      },
    },
  },
  "analog-monochrome-monitor": {
    opacity: {
      key: "opacity",
      label: "Opacity",
      type: "number",
      value: 1.0,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    pixelSize: {
      key: "pixelSize",
      label: "Pixel size",
      type: "number",
      value: 0.01,
      min: 0.001,
      max: 0.1,
      step: 0.001,
    },
    greyscale: {
      key: "greyscale",
      label: "Grey scale",
      type: "boolean",
      value: true,
    },
    contrast: {
      key: "contrast",
      label: "Contrast",
      type: "number",
      value: 1.0,
      min: 0.0,
      max: 5.0,
      step: 0.1,
    },
    pixelColors: {
      key: "pixelColors",
      label: "Pixel colors",
      type: "color",
      value: "#ffffff",
    },
    backgroundColor: {
      key: "backgroundColor",
      label: "Background color",
      type: "color",
      value: "#000000",
    },
  },
  bloom: {
    strength: {
      key: "strength",
      label: "Strength",
      type: "number",
      value: 1.0,
      min: 0.0,
      max: 10.0,
      step: 0.05,
    },
    radius: {
      key: "radius",
      label: "Radius",
      type: "number",
      value: 8.0,
      min: 1.0,
      max: 50.0,
      step: 0.5,
    },
    threshold: {
      key: "threshold",
      label: "Threshold",
      type: "number",
      value: 0.5,
      min: 0.0,
      max: 1.0,
      step: 0.01,
    },
    softness: {
      key: "softness",
      label: "Softness",
      type: "number",
      value: 0.5,
      min: 0.01,
      max: 1.0,
      step: 0.01,
    },
    saturationWeight: {
      key: "saturationWeight",
      label: "Saturation weight",
      type: "number",
      value: 1.0,
      min: 0.0,
      max: 2.0,
      step: 0.05,
    },
  },
};
