import type { Effect, EffectInput } from "@/types";

export const OPTIONS_WIDTH = 400;

export const EFFECTS: Effect[] = ["none", "tint", "warp", "crt-vhs", "crt", "lens-array", "metal-core", "posterize"];

export const EFFECT_NAMES: Record<Effect, string> = {
  none: "Ninguno",
  tint: "Tint",
  warp: "Warp",
  "crt-vhs": "CRT VHS",
  crt: "CRT",
  "lens-array": "Lens Array",
  "metal-core": "Metal Core",
  posterize: "Posterize",
};

export const EFFECT_DEFAULTS: Record<Exclude<Effect, "none">, Record<string, EffectInput>> = {
  tint: {
    color: {
      key: "color",
      label: "Color",
      type: "color",
      value: "#ff0055",
    },
    opacity: {
      key: "opacity",
      label: "Opacity",
      type: "number",
      value: 0.8,
      min: 0,
      max: 1,
    },
  },
  warp: {
    intensity: {
      key: "intensity",
      label: "Intensity",
      type: "number",
      value: 0.05,
      min: 0,
      max: 1,
    },
  },
  "crt-vhs": {
    scanlinesOpacity: {
      key: "scanlinesOpacity",
      label: "Scanlines_Opacity",
      type: "number",
      value: 0.4,
      min: 0,
      max: 1,
    },
    scanlinesWidth: {
      key: "scanlinesWidth",
      label: "Scanlines_Width",
      type: "number",
      value: 0.25,
      min: 0,
      max: 1,
    },
    grilleOpacity: {
      key: "grilleOpacity",
      label: "Grille_Opacity",
      type: "number",
      value: 0.3,
      min: 0,
      max: 1,
    },
    pixelate: {
      key: "pixelate",
      label: "Pixelate",
      type: "boolean",
      value: true,
    },
    roll: {
      key: "roll",
      label: "Roll",
      type: "boolean",
      value: true,
    },
    rollSpeed: {
      key: "rollSpeed",
      label: "Roll_Speed",
      type: "number",
      value: 8.0,
      min: 0,
      max: 32,
    },
    rollSize: {
      key: "rollSize",
      label: "Roll_Size",
      type: "number",
      value: 15.0,
      min: 0,
      max: 100,
      step: 1,
    },
    rollVariation: {
      key: "rollVariation",
      label: "Roll_Variation",
      type: "number",
      value: 1.8,
      min: 0,
      max: 10,
    },
    distortIntensity: {
      key: "distortIntensity",
      label: "Distort_Intensity",
      type: "number",
      value: 0.05,
      min: 0,
      max: 1,
    },
    noiseOpacity: {
      key: "noiseOpacity",
      label: "Noise_Opacity",
      type: "number",
      value: 0.4,
      min: 0,
      max: 1,
    },
    noiseSpeed: {
      key: "noiseSpeed",
      label: "Noise_Speed",
      type: "number",
      value: 5.0,
      min: 0,
      max: 50,
    },
    staticNoiseIntensity: {
      key: "staticNoiseIntensity",
      label: "Static_Noise_Intensity",
      type: "number",
      value: 0.06,
      min: 0,
      max: 1,
    },
    aberration: {
      key: "aberration",
      label: "Aberration",
      type: "number",
      value: 0.03,
      min: 0,
      max: 1,
    },
    brightness: {
      key: "brightness",
      label: "Brightness",
      type: "number",
      value: 1.4,
      min: 0,
      max: 10,
    },
    discolor: {
      key: "discolor",
      label: "Discolor",
      type: "boolean",
      value: true,
    },
    warpAmount: {
      key: "warpAmount",
      label: "Warp_Amount",
      type: "number",
      value: 1.0,
      min: 0,
      max: 10,
      step: 1,
    },
    clipWarp: {
      key: "clipWarp",
      label: "Clip_Warp",
      type: "boolean",
      value: false,
    },
    vignetteIntensity: {
      key: "vignetteIntensity",
      label: "Vignette_Intensity",
      type: "number",
      value: 0.4,
      min: 0,
      max: 1,
    },
    vignetteOpacity: {
      key: "vignetteOpacity",
      label: "Vignette_Opacity",
      type: "number",
      value: 0.5,
      min: 0,
      max: 1,
    },
  },
  crt: {
    pixelSize: {
      key: "pixelSize",
      label: "Pixel_Size",
      type: "number",
      value: 8.0,
      min: 1,
      max: 50,
      step: 1,
    },
  },
  "lens-array": {
    gridSize: {
      key: "gridSize",
      label: "Grid_Size",
      type: "number",
      value: 50.0,
      min: 1,
      max: 100,
      step: 1,
    },
    curvature: {
      key: "curvature",
      label: "Curvature",
      type: "number",
      value: 0.25,
      min: 0,
      max: 1,
    },
    gridAngle: {
      key: "gridAngle",
      label: "Grid_Angle",
      type: "number",
      value: 0.0,
      min: 0,
      max: 1,
    },
    shape: {
      key: "shape",
      label: "Shape",
      type: "select",
      value: 0,
      options: [
        {
          label: "Círculo",
          value: 0,
        },
        {
          label: "Diamante",
          value: 1,
        },
        {
          label: "Cuadrado",
          value: 2,
        },
      ],
    },
    scale: {
      key: "scale",
      label: "Scale",
      type: "array-2",
      value: [1, 1],
      min: 0,
      max: 100,
      step: 1,
    },
    stagger: {
      key: "stagger",
      label: "Stagger",
      type: "boolean",
      value: true,
    },
  },
  "metal-core": {
    exposure: {
      key: "exposure",
      label: "Exposure",
      type: "number",
      value: 1.0,
      min: 0,
      max: 2,
    },
    contrast: {
      key: "contrast",
      label: "Contrast",
      type: "number",
      value: 1.05,
      min: 0,
      max: 2,
    },
    saturation: {
      key: "saturation",
      label: "Saturation",
      type: "number",
      value: 0.9,
      min: 0,
      max: 2,
    },
    enablePixelate: {
      key: "enablePixelate",
      label: "Enable_Pixelate",
      type: "boolean",
      value: true,
    },
    pixelFactor: {
      key: "pixelFactor",
      label: "Pixel_Factor",
      type: "number",
      value: 2.0,
      min: 1,
      max: 100,
    },
    enablePosterize: {
      key: "enablePosterize",
      label: "Enable_Posterize",
      type: "boolean",
      value: true,
    },
    colorLevels: {
      key: "colorLevels",
      label: "Color_Levels",
      type: "number",
      value: 8.0,
      min: 1,
      max: 64,
      step: 1,
    },
    ditherStrength: {
      key: "ditherStrength",
      label: "Dither_Strength",
      type: "number",
      value: 0.35,
      min: 0,
      max: 1,
    },
    chromAberration: {
      key: "chromAberration",
      label: "Chrom_Aberration",
      type: "number",
      value: 0.35,
      min: 0,
      max: 1,
    },
    vignetteStrength: {
      key: "vignetteStrength",
      label: "Vignette_Strength",
      type: "number",
      value: 1.0,
      min: 0,
      max: 10,
    },
    grainStrength: {
      key: "grainStrength",
      label: "Grain_Strength",
      type: "number",
      value: 0.2,
      min: 0,
      max: 10,
    },
    tintColor: {
      key: "tintColor",
      label: "Tint_Color",
      type: "array-3",
      value: [0.95, 1.03, 0.9],
      min: 0,
      max: 255,
      step: 1,
    },
    tintStrength: {
      key: "tintStrength",
      label: "Tint_Strength",
      type: "number",
      value: 0.15,
      min: 0,
      max: 1,
    },
    viewportSize: {
      key: "viewportSize",
      label: "Viewport_Size",
      type: "array-2",
      value: [0, 0],
      min: 0,
      max: 1000,
      step: 1,
    },
  },
  posterize: {
    noiseScale: {
      key: "noiseScale",
      label: "Noise_Scale",
      type: "number",
      value: 1.0,
      min: 1,
      max: 100,
      step: 1,
    },
    colorLevels: {
      key: "colorLevels",
      label: "Color_Levels",
      type: "number",
      value: 4,
      min: 0,
      max: 64,
      step: 1,
    },
    ditherStrength: {
      key: "ditherStrength",
      label: "Dither_Strength",
      type: "number",
      value: 0.5,
      min: 0,
      max: 1,
    },
  },
};
